### ISSUE TITLE
Tool hangs and produces high CPU usage

### ISSUE THREAD

**Issue by si9int** [harleo/asnip#7]

**Comment by harleo** [comment]
Hello @si9int,

thanks for reporting this issue. It should be fixed with commit https://github.com/harleo/asnip/commit/7bf449c1df44ee2b0680ddac27bc3031384a623f. Apparently it had to do with the exclusion of network and broadcast addresses in the conversion of CIDRs to IPs resulting in out of bounds.

Thanks.
